### ISSUE TITLE
Feature Request: Inline Links open New Tab Option

### ISSUE THREAD

**Issue by ErikPlachta** [builduilabs/framer-motion-recipes#3]
## Request

When link to external resource, then have option to open in new tab 

## Why

It's nice to have the resource page opened along side content.

## Example

For example,links on bottom of page 
> https://buildui.com/series/framer-motion-recipes/email-client 

![image](https://user-images.githubusercontent.com/17508965/208737165-e8361701-6d84-4e8d-b1f1-d74d71af1e5d.jpeg)

**Comment by samselikoff** [comment]
Whoops missed this one! Believe this one is taken care of, can you confirm?

I need to subscribe to my own repos in the future ^_^
