### ISSUE TITLE
4-header-part-2 on scroll  not working 

### ISSUE THREAD

**Issue by Chethannp** [builduilabs/framer-motion-recipes#4]
Downloading this repo on my local and running it the header shrinks as per expectation but when I set up a new NextJs project it does not work :( could you please help 

https://drive.google.com/file/d/19jz3GvQTRIh73N3-O6xntav4mgrvFCuS/view?usp=sharing

dependencies:
 "@next/font": "13.1.5",
  "eslint": "8.32.0",
  "eslint-config-next": "13.1.5",
  "framer-motion": "^8.5.2",
  "next": "13.1.5",
  "react": "18.2.0",
  "react-dom": "18.2.0"

VS code Error: 
The signature '(subscription: Subscriber<number>): () => void' of 'scrollY.onChange' is deprecated.ts(6387)
index.d.ts(1773, 8): The declaration was marked as deprecated here.

**Comment by samselikoff** [comment]
Sorry about the delay on this!

`onChange` was deprecated but it should still work, but to update it to the new syntax of `.on` here's what you should change:

![image](https://user-images.githubusercontent.com/2922250/215804060-66f40c7a-4399-480a-a91f-36d5ab031bce.png)

I just upgraded all the deps in the repo to their latest over here and the header is working. Can you share some of your code?

**Comment by Chethannp** [comment]
Thank you! it is working fine.
