### ISSUE TITLE
onChange won't work anymore

### ISSUE THREAD

**Issue by syedsimanta03** [builduilabs/framer-motion-recipes#6]
we can't use onChange for the fixed header as it's deprecated

**Comment by samselikoff** [comment]
You can replace it with `.on("change", val =>` like this:

```diff
   );
 
   useEffect(() => {
-    return scrollY.onChange((current) => {
+    return scrollY.on("change", (current) => {
       let previous = scrollY.getPrevious();
       let diff = current - previous;
       let newScrollYBounded = scrollYBounded.get() + diff;
```

Adding a recipe to Build UI now so I can keep this code updated!

**Comment by samselikoff** [comment]
Ok here's the recipe for future reference!

https://buildui.com/recipes/fixed-header
